<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><Compile Include="../../src/MeadStoragePolicy.cs" Link="MeadStoragePolicy.cs"/><Compile Include="../../src/MeadCabinet.cs" Link="MeadCabinet.cs"/><Compile Include="../../src/Cosmetics/OwlModelData.cs" Link="OwlModelData.cs"/></ItemGroup></Project>
