<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <NoWarn>CS8632</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/SharedChestCore.cs" Link="SharedChestCore.cs" />
  </ItemGroup>
</Project>
