<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><OutputType>Exe</OutputType><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><Compile Include="../../src/DeliveryHistory.cs" Link="DeliveryHistory.cs"/><Reference Include="Newtonsoft.Json"><HintPath>/home/deck/.steam/steam/steamapps/common/Valheim/valheim_Data/Managed/Newtonsoft.Json.dll</HintPath></Reference></ItemGroup></Project>