using Quartermaster;
using UnityEngine;
using Jotunn.Managers;
int checks=0;
void Check(bool pass,string message){checks++;if(!pass)throw new Exception(message);}
var oldItem=new GameObject("Flint");var oldArt=new GameObject("old art");var item=new GameObject(ClayResource.ItemName);var art=new GameObject("clay");
var picked=new Pickable{m_itemPrefab=oldItem,m_hideWhenPicked=oldArt,m_defaultPicked=true,m_defaultEnabled=false,m_respawnTimeInitMin=20,m_respawnTimeInitMax=60,m_harvestable=true,m_extraDrops=new()};var oldDrops=picked.m_extraDrops;
ClayResource.Configure(picked,item,art);
Check(picked.m_itemPrefab==item&&picked.m_itemPrefab!=oldItem,"drop own item, never template flint");
Check(picked.m_hideWhenPicked==art&&picked.m_hideWhenPicked!=oldArt,"native picked state hides the original replacement art");
Check(picked.m_amount==3&&!picked.m_dontScale&&picked.m_minAmountScaled==1,"three clay per patch respects native resource modifier");
Check(picked.m_respawnTimeMinutes==240&&picked.m_respawnTimeInitMin==0&&picked.m_respawnTimeInitMax==0,"native four-hour respawn, no initial harvest delay");
Check(picked.m_defaultEnabled&&!picked.m_defaultPicked&&!picked.m_harvestable,"available resource, not farm-crop behavior");
Check(picked.m_extraDrops!=oldDrops,"clear any inherited extra drops");
Check(picked.m_overrideName=="$item_quartermaster_rawclay","own localized hover label");
var placement=ClayResource.Placement();
Check(placement.Biome==(Heightmap.Biome.Meadows|Heightmap.Biome.BlackForest),"early-biome shorelines only");
Check(placement.MinAltitude>=0&&placement.MaxAltitude<=2.5f,"accessible shore bank, not underwater or upland");
Check(placement.Min==0&&placement.Max<=4&&placement.GroupSizeMax<=2,"bounded sparse native generation");
Check(placement.BlockCheck&&!placement.ForcePlacement,"native obstacle checks, no forced placement");
Check(placement.MaxTilt<=25,"no steep cliff patches");
Check(placement.ScaleMin>0&&placement.ScaleMax<=1.2f,"bounded size variation");
ClayResource.Initialize();PrefabManager.Fire();
Check(Plugin.Log.Errors.Count==0,"registration succeeds");
Check(ItemManager.Instance.Items.Count==1&&ZoneManager.Instance.Entries.Count==1,"one item and one networked vegetation registration");
var registered=ItemManager.Instance.Items[0].ItemPrefab;var patch=ZoneManager.Instance.Entries[0].Prefab;
Check(registered.name==ClayResource.ItemName&&patch.name==ClayResource.PickableName,"stable unique prefab names");
Check(PrefabManager.Instance.Clones.Select(x=>x.source).SequenceEqual(new[]{"Flint","Pickable_Flint"}),"only vanilla behavior templates used");
Check(ClayModel.Replaced.Count==2&&ClayModel.Replaced[0].patch==false&&ClayModel.Replaced[1].patch,"replace both item and ground visuals");
Check(patch.Pick.m_itemPrefab==registered,"world pickup points to registered clay item");
Check(patch.View.m_syncInitialScale,"native network clients receive ground patch scale");
Check(registered.Item.m_itemData.m_dropPrefab==registered&&registered.Item.m_itemData.m_stack==1,"routing identity binds to clay, not the cloned native template");
var data=registered.Item.m_itemData.m_shared;
Check(data.m_icons.Length==1&&data.m_name=="$item_quartermaster_rawclay","own inventory icon and name");
Check(data.m_weight==1&&data.m_value==0&&data.m_teleportable,"material balance and portal behavior");
Check(ItemStacks.Applied==1&&data.m_maxStackSize==500,"late custom item observes current stack override");
Check(LocalizationManager.Instance.Words.Count==2,"both item and description localized");
PrefabManager.Fire();Check(ItemManager.Instance.Items.Count==1&&ZoneManager.Instance.Entries.Count==1,"repeated prefab event cannot duplicate registrations");
ClayResource.Shutdown();PrefabManager.Fire();Check(ItemManager.Instance.Items.Count==1,"shutdown leaves no registration callback");
Console.WriteLine($"PASS: {checks} original clay registration, yield, respawn, placement, identity and stack-policy checks.");
